#! /bin/sh

sxhkd &
picom -b
~/.config/polybar/launch.sh
feh --bg-scale ~/Pictures/blue-landscape.jpg
~/Documents/scripts/battery_low_warn &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.58
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Glade-previewer state=floating

# color
bspc config normal_border_color  "#74737c"
bspc config focused_border_color "#093748"
bspc config urgent_border_color  "#c33027"

# startup application (executed once)
~/Documents/scripts/startup.sh &
