#! /bin/sh

sxhkd &
# transparency
# picom -b
~/.config/polybar/launch.sh
# set up background image
# feh --bg-scale ~/Pictures/gnome-background.jpg
# simple script to warn battery low
~/Documents/scripts/battery_low_warn &
xsetroot -cursor_name left_ptr &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           7

bspc config split_ratio          0.58
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Glade-previewer state=floating
bspc rule -a discord desktop="^4"

# color
bspc config normal_border_color  "#74737c"
bspc config focused_border_color "#26a98b"
bspc config urgent_border_color  "#c33027"

# startup application (executed once)
~/Documents/scripts/startup.sh &


